### ISSUE TITLE
Alfred 2 Extension - Only works with single search term

### ISSUE THREAD

**Issue by taylorjason** [ttscoff/QuickQuestion#12]
I am running Alfred 2 and downloaded the Alfred 2 extension.  QA script works fine and creates the question answer file.  However, when I attempt to search with qq the search only works if I use a single word query.  I can use any word in the title and it will work however if I use multiple words it will not find anything and I get the "sorry, I don't know the answer to that question".

For example, my question is "How does this work".  Answer "Magic"
If I enter "qq how" the search works
If I enter "qq how work", it says it doesn't know the answer.

Running Alfred 2 on Mavericks.  I know there were a few other posts similar but none of those solutions worked for me.

My current script that I pulled from GitHub is as follows:

``` bash
#Desc:  Ask a question using the qq script. Edit the configuration variables below based on your setup.
#Use:   qq {query}
#Ex:    qq where glasses

# notes folder, for note creation and limiting searches
NOTESDIR="/Users/jasontaylor/Dropbox/Notational Data/"
# extension used for your notes
NOTESEXT="md"
# the prefix you use to separate "Question" notes
NOTESPRE="??"

INPUT="{query}"
echo "`mdfind -onlyin \"$NOTESDIR\" \"filename:$NOTESEXT AND filename:$NOTESPRE AND ${INPUT%\?}\"`"|while read LINE; do
    if [[ "$LINE" == "" ]]; then 
      echo "Sorry, I don't know the answer to that question."
      exit 1;
    fi
    QUESTION=${LINE##*/}
    echo -n "Q: "
    NOTESPREESC=`echo "$NOTESPRE"|sed -E 's/([\?\!\$\`\"]) ?/\\\\\1/g'`
    echo ${QUESTION%%$NOTESEXT}|sed -E "s/$NOTESPREESC ?//g"|sed -E 's/(.)$/\1?/'
    echo -n "A: "
    cat "$LINE"|sed -E 's/@\([^\)]+\) ?//g'|sed -E 's/@copy\(([^)]*)\)/\1/'|tr -s "\n"|sed -E 's/^[   ]*|[  ]*$//g'
    if [[ `cat "$LINE"|grep -E '@copy\('` ]]; then
        cat "$LINE"|grep '@copy('|sed -E 's/.*@copy\(([^)]*)\).*/\1/'|tr -d '\n'|pbcopy
        echo "Example in clipboard"
    fi
    echo
done
```

**Comment by dericco** [comment]
Even though this question is quite old I found a solution to this issue:
You need to make sure that 'Escaping Spaces' is not activated for the 'Run Script' action. Otherwise Alfred prefixes spaces with backslashes which confuses mdfind.

**Comment by brianroach** [comment]
@dericco so I did what you said, and it at least recognizes my search query, but it doesn't actually return the answer. It's just blank. Do you know how to fix this?

![2016-04-08 at 10 45 am](https://cloud.githubusercontent.com/assets/9772694/14392624/1ee19b26-fd77-11e5-8e8a-6f76c6660e15.jpg)

**Comment by dericco** [comment]
Sorry @brianroach, I don't know. Does the text file look as expected with just the answer in the first line? Would it work when you create the question without the apostrophe?
If not, you might be able to find the reason when trying the mdfind command in Terminal.
